quizC:AnswerQ.o audio.o close.o display.o init.o input.o main.o media.o play.o QuestionFile.o
	gcc AnswerQ.o audio.o close.o display.o init.o input.o main.o media.o play.o QuestionFile.o -o quizC -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
AnswerQ.o:AnswerQ.c
	gcc -c AnswerQ.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
audio.o:audio.c
	gcc -c audio.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
close.o:close.c
	gcc -c close.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
display.o:display.c
	gcc -c display.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
init.o:init.c
	gcc -c init.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
input.o:input.c
	gcc -c input.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
media.o:media.c
	gcc -c media.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
play.o:play.c
	gcc -c play.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
QuestionFile.o:QuestionFile.c
	gcc -c QuestionFile.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
