p:main.o  perso.o
	gcc  main.o perso.o -o p -lSDL  -lSDL_image -lSDL_mixer -lSDL_ttf -g
main.o:main.c
	gcc -c main.c  -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf  -g
perso.o:perso.c
	gcc -c perso.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
